# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d61b9e4cb85e01ab3bfc0566c2a0c2edcfdc6159a9794da3a97b4aca8087e734066341100d398086305d12f65200f6e663572dd0423173aa330d07b633ef28a4

test:
  secret_key_base: 3424931c5a499ac3adbaca9c7c1db40d8d62e1876abe3dfa219e49a4d4885919056d6d01f9958140e6bf2c1c5f26a04abf25dec71352bb83fda4ff33c6afb61f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
